#!/usr/bin/env python3
"""
build.py -- generate the project map.

    python3 -m scripts.project_map.build            # model.json + standalone HTML
    python3 -m scripts.project_map.build --check    # also run the consistency checks (test_model.py,
                                                    # test_sim.mjs with node) and fail if the
                                                    # committed files are out of date

Outputs (committed, so the site and the offline file never need pyslang):
    docs/assets/project_map/model.json
    docs/assets/project_map/regmap.js      (the register map of regmap.yaml, for sim.js)
    docs/downloads/yapp_project_map.html
    docs/test-plan.md                      (the feature matrix and the tests of annotations.yaml plan: / tests:)
"""
import argparse
import html
import json
import os
import re
import subprocess
import sys

import yaml
from jinja2 import Template

from . import extract, layout, model

ROOT = extract.ROOT
HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(ROOT, "docs", "assets", "project_map")
MODEL_JSON = os.path.join(ASSETS, "model.json")
STANDALONE = os.path.join(ROOT, "docs", "downloads", "yapp_project_map.html")
REGMAP_YAML = os.path.join(HERE, "regmap.yaml")
REGMAP_JS = os.path.join(ASSETS, "regmap.js")
TEST_PLAN_MD = os.path.join(ROOT, "docs", "test-plan.md")
GENERATED = {}      # path -> content of the last build (for the staleness check)

STATUS_WORD = {"covered": "covered", "partial": "partial", "gap": "gap", "excluded": "excluded"}
STATUS_MARK = {k: f'<span class="st st-{k}">{k}</span>' for k in STATUS_WORD}


def md_cell(text):
    """One table cell: no pipes, no line breaks."""
    return " ".join(str(text or "").replace("|", "\\|").split())


def render_test_plan_md(m):
    """docs/test-plan.md from the plan and the tests of the model: one section per feature
    group with its item table, then every test with the items it verifies."""
    plan = m["plan"]
    N = m["nodes"]
    items = [it for g in plan for it in g["items"]]
    counts = {k: sum(1 for it in items if it["status"] == k) for k in STATUS_WORD}
    out = []
    out.append("# Test plan\n")
    out.append("<!-- generated by scripts/project_map/build.py from scripts/project_map/annotations.yaml "
               "(plan: and tests:) -- edit the YAML and run `make map`; do not edit this file -->\n")
    out.append("[Open the Test plan view of the project map →](project-map.md#view=plan){ .pm-link }\n")
    out.append("A verification plan links every **feature** of the DUT to the **stimulus** that exercises it, "
               "the **checker** that judges it and the **coverage** that proves it happened. This plan follows "
               "the pages of the course's DUT description (packet format, input and output protocols, "
               "registers, drop rules, counters, memories, host port) and the lab chapters that add "
               "requirements of their own (scoreboard, functional coverage, register tests). "
               f"**{len(plan)} feature groups, {len(items)} items**: "
               + ", ".join(f"{counts[k]} {STATUS_MARK[k]}" for k in STATUS_WORD if counts[k]) + ".\n")
    out.append("Every item says what is driven, what is checked and by which test; a *partial* item is exercised "
               "but not fully checked, a *gap* has no test yet (the note says what one would do), an *excluded* "
               "item is left out on purpose. The same data drives the **Test plan** view of the "
               "[project map](project-map.md), where every test card lists the items it verifies.\n")
    out.append("## Features\n")
    for g in plan:
        out.append(f"### {g['id']} — {g['title']}\n")
        src = f"*{md_cell(g['spec'])}.*" if g.get("spec") else ""
        link = f" [Read the specification →]({g['doc']})" if g.get("doc") and not g["doc"].startswith("labs/") else (f" [The lab →]({g['doc']})" if g.get("doc") else "")
        out.append(f"{md_cell(g['summary'])} {src}{link} "
                   f"[On the map →](project-map.md#view=plan&node=plan:{g['id']})\n")
        out.append("| Item | What is verified, and how | Tests |")
        out.append("|---|---|---|")
        for it in g["items"]:
            tests = "<br>".join(f"`{t}`" for t in it["tests"]) or "—"
            cell = [f"**{md_cell(it['title'])}**"]
            if it["stimulus"] != "--":
                cell.append(f"*Stimulus:* {md_cell(it['stimulus'])}")
            if it["check"] != "--":
                cell.append(f"*Check:* {md_cell(it['check'])}")
            if it.get("coverage"):
                cell.append(f"*Coverage:* `{md_cell(it['coverage'])}`")
            if it.get("note"):
                cell.append(f"*Note:* {md_cell(it['note'])}")
            out.append(f"| **{it['id']}**<br>{STATUS_MARK[it['status']]} | {'<br>'.join(cell)} | {tests} |")
        out.append("")
    scene = next((s for s in m["scenes"] if s["id"] == "plan:main"), None)
    order = [it["id"] for it in scene["items"] if it.get("style") == "test_card"] if scene else []
    out.append("## Coverage matrix\n")
    out.append("Who verifies what, at a glance: one row per plan item, one column per test (in course order, "
               "the test-plan tests last); a dot where the test covers the item, in the colour of the item's "
               "status. The last column counts the tests of an item, the last row the items of a test. "
               "Hover a dot for the pair.\n")
    out.extend(render_matrix_html(plan, N, order))
    out.append("")
    out.append("## Tests\n")
    out.append("Every test extends `base_test` and only changes what runs. The lab is where the test was born; "
               "the test-plan tests exist only in `yapp_project/tb/tests`. Run one with "
               "`make run-project TEST=<name>` (or `make run LAB=<lab> TEST=<name>` for a lab).\n")
    out.append("| Test | Lab | Purpose | Verifies |")
    out.append("|---|---|---|---|")
    for nid in order:
        n = N[nid]
        lab_doc = next((d["url"] for d in n.get("docs", []) if d["title"].startswith("Lab")), None)
        lab = "test plan" if n.get("lab") == "TP" else (f"[{n['lab']}]({lab_doc})" if lab_doc else str(n.get("lab") or "—"))
        plan_ = n.get("plan") or {}
        verifies = ", ".join(c["id"] for c in n.get("covers", [])) or "—"
        out.append(f"| `{n['name']}` | {lab} | {md_cell(plan_.get('purpose') or n.get('summary'))} | {verifies} |")
    out.append("")
    out.append("## Writing a new test — checklist\n")
    out.append("1. Extend `base_test` (or `reg_function_test` when you need the register block, the YAPP sequencer and `check_counter()`); add `` `uvm_component_utils `` and the constructor.")
    out.append("2. Decide the packet type: factory override in `build_phase` *before* `super.build_phase(phase)`.")
    out.append("3. `configure_sequences()`: which sequencer runs what. Always `set_clock_and_channel_sequences()` in Labs 7+ (or your own channel sequence, as `backpressure_test` does).")
    out.append("4. For register tests: get handles in `connect_phase`, raise an objection in `run_phase`, use the model API.")
    out.append("5. Decide what *passes*: `UVM_ERROR : 0` plus the counts in the reports, and say so in the log (`uvm_info` at `UVM_NONE`).")
    out.append("6. Add the test to `annotations.yaml`: a line under `classes:`, its plan under `tests:`, and the items it verifies under `plan:`; `make map` regenerates this page and the map.")
    out.append("")
    return "\n".join(out)


def render_matrix_html(plan, N, order):
    """The items x tests matrix as one HTML table (Markdown tables cannot rotate headers or
    colour cells): a group row per feature group, a dot per (item, test) pair."""
    tests = [N[nid]["name"] for nid in order]
    ncols = len(tests) + 3
    esc = html.escape
    rows = ['<div class="mx-wrap" markdown="0">', '<table class="mx">', "<thead><tr>",
            '<th class="mx-item">Item</th>',
            *(f'<th class="mx-t"><span>{esc(t)}</span></th>' for t in tests),
            '<th class="mx-n">tests</th>', "</tr></thead>", "<tbody>"]
    per_test = {t: 0 for t in tests}
    for g in plan:
        rows.append(f'<tr class="mx-g"><th colspan="{ncols - 1}">{esc(g["id"])} · {esc(g["title"])}</th></tr>')
        for it in g["items"]:
            cells = []
            for t in tests:
                if t in it["tests"]:
                    per_test[t] += 1
                    cells.append(f'<td class="mx-c st-{it["status"]}" title="{esc(it["id"])} ← {esc(t)}">●</td>')
                else:
                    cells.append('<td class="mx-c"></td>')
            rows.append(f'<tr><th class="mx-item st-{it["status"]}" title="{esc(md_cell(it["title"]))}">'
                        f'<b>{esc(it["id"])}</b> <span>{esc(md_cell(it["title"]))}</span></th>'
                        + "".join(cells) + f'<td class="mx-n">{len(it["tests"]) or "–"}</td></tr>')
    rows.append('<tr class="mx-sum"><th class="mx-item">items per test</th>'
                + "".join(f'<td class="mx-n">{per_test[t]}</td>' for t in tests) + "<td></td></tr>")
    rows.extend(["</tbody>", "</table>", "</div>"])
    return rows


def load_regmap():
    with open(REGMAP_YAML, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def read_asset(name):
    with open(os.path.join(ASSETS, name), encoding="utf-8") as fh:
        return fh.read()


def site_config():
    with open(os.path.join(ROOT, "mkdocs.yml"), encoding="utf-8") as fh:
        txt = fh.read()
    repo = re.search(r"^repo_url:\s*(\S+)", txt, re.M)
    site = re.search(r"^site_url:\s*(\S+)", txt, re.M)
    return (repo.group(1) if repo else ""), (site.group(1) if site else "")


def build(write=True):
    ann = model.load_annotations()
    m = model.build_model(ann)
    m["meta"]["regmap"] = load_regmap()
    scenes, where = layout.build_scenes(m, ann)
    m["scenes"] = scenes
    m["where"] = where
    repo_url, site_url = site_config()
    m["meta"]["repo_url"] = repo_url
    m["meta"]["site_url"] = site_url
    # compact, deterministic JSON
    model_json = json.dumps(m, indent=None, separators=(",", ":"), sort_keys=True, ensure_ascii=False)
    regmap_js = ("// generated by scripts/project_map/build.py from scripts/project_map/regmap.yaml -- do not edit\n"
                 "window.YAPP_REGMAP = " + json.dumps(m["meta"]["regmap"], indent=1, sort_keys=True) + ";\n")
    with open(os.path.join(HERE, "templates", "standalone.html.j2"), encoding="utf-8") as fh:
        tpl = Template(fh.read())
    html = tpl.render(
        app_css=read_asset("app.css"), app_js=read_asset("app.js"),
        sim_css=read_asset("sim.css"), sim_js=read_asset("sim.js"), regmap_js=regmap_js,
        model_json=model_json.replace("</", "<\\/"),
        repo_url=repo_url, docs_base=site_url, page_url=(site_url + "project-map/") if site_url else "",
    )
    GENERATED.clear()
    GENERATED.update({MODEL_JSON: model_json, REGMAP_JS: regmap_js, STANDALONE: html, TEST_PLAN_MD: render_test_plan_md(m)})
    if write:
        os.makedirs(os.path.dirname(STANDALONE), exist_ok=True)
        for path, content in GENERATED.items():
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
    return m, model_json, html


def check_sim():
    """Behavioural checks of sim.js (RouterModel) with node, when node is available."""
    import shutil
    node = shutil.which("node")
    if not node:
        print("sim checks: skipped (node not found); run `node scripts/project_map/test_sim.mjs`")
        return True
    proc = subprocess.run([node, os.path.join(HERE, "test_sim.mjs")], cwd=ROOT)
    return proc.returncode == 0


def check(m, model_json, html):
    from . import test_model
    test_model.run_all(m, model_json, html)
    if not check_sim():
        return False
    # staleness: the committed files must match what we just generated
    stale = []
    for path, content in GENERATED.items():
        try:
            with open(path, encoding="utf-8") as fh:
                if fh.read() != content:
                    stale.append(os.path.relpath(path, ROOT))
        except OSError:
            stale.append(os.path.relpath(path, ROOT))
    if stale:
        print("STALE: regenerate with `make map` and commit:", ", ".join(stale))
        return False
    return True


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="run the checks and verify the committed files are current")
    ns = ap.parse_args()
    m, model_json, html = build(write=not ns.check)
    print(f"project map: {len(m['nodes'])} nodes, {len(m['edges'])} edges, {len(m['scenes'])} scenes, "
          f"model {len(model_json) // 1024} KB, standalone {len(html) // 1024} KB")
    if m["unresolved"]:
        print("unresolved connections:")
        for u in m["unresolved"]:
            print("  ", u)
        sys.exit(1)
    if ns.check and not check(m, model_json, html):
        sys.exit(1)
    if not ns.check:
        print("wrote " + ", ".join(os.path.relpath(p, ROOT) for p in GENERATED))


if __name__ == "__main__":
    main()
