#!/usr/bin/env python3
"""
extract.py -- pull the structure of the UVM testbench and the DUT out of the
SystemVerilog source with pyslang (slang).

The output is a plain dictionary ("raw structure"): classes with their base
chain, members, TLM ports and the connect()/set_sequencer()/handle assignments
of their connect_phase, the config_db set() calls, the vif bindings of tb_top,
the hw_top instance tree, the DUT internals and the interface signals.
model.py turns it into the project-map model; annotations.yaml adds the prose.

    python3 -m scripts.project_map.extract labs/lab11c_rm_sim/tb/run.f   # prints a summary
"""
import json
import os
import re
import sys

import pyslang

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import lint  # noqa: E402  (scripts/lint.py: parse_run_f, standard_args, compile_run_f)

SK = pyslang.ast.SymbolKind

# members generated by the `uvm_*_utils / field macros -- never shown
MACRO_MEMBERS = {
    "type_id", "get_type", "get_object_type", "create", "type_name", "get_type_name",
    "do_execute_op", "__m_uvm_execute_field_op", "__m_uvm_field_automation",
    "m_registered_type", "get_randstate", "set_randstate", "srandom", "rand_mode",
    "constraint_mode", "randomize",
}
TLM_PORT_RE = re.compile(
    r"^(uvm_analysis_port|uvm_analysis_export|uvm_analysis_imp\w*|uvm_tlm_analysis_fifo|"
    r"uvm_seq_item_pull_port|uvm_seq_item_pull_export|uvm_get_port|uvm_blocking_get_port|"
    r"uvm_put_port|uvm_blocking_put_port|uvm_tlm_fifo)")


def _members(sym):
    try:
        return list(sym)
    except TypeError:
        return []


def _kind(sym):
    return str(sym.kind).split(".")[-1]


class Extractor:
    def __init__(self, comp, rel_root=ROOT):
        self.comp = comp
        self.sm = comp.sourceManager
        self.rel_root = rel_root
        self._buf_cache = {}

    # ----------------------------------------------------------------- helpers
    def text(self, rng):
        """Source text of a range. slang offsets are BYTE offsets."""
        if rng is None:
            return ""
        buf = rng.start.buffer
        if buf not in self._buf_cache:
            self._buf_cache[buf] = self.sm.getSourceText(buf).encode("utf-8")
        return self._buf_cache[buf][rng.start.offset:rng.end.offset].decode("utf-8", "replace")

    def file_of(self, loc):
        name = self.sm.getFileName(loc)
        try:
            return os.path.relpath(os.path.abspath(name), self.rel_root).replace(os.sep, "/")
        except ValueError:
            return name

    def line_of(self, loc):
        return self.sm.getLineNumber(loc)

    def span(self, sym):
        """(line, end_line) from the symbol's syntax node."""
        line = self.line_of(sym.location)
        end = line
        try:
            if sym.syntax is not None:
                end = self.line_of(sym.syntax.sourceRange.end)
        except Exception:
            pass
        return line, end

    @staticmethod
    def type_name(t):
        """Generic class name without the parameter list (uvm_sequence #(x) -> uvm_sequence)."""
        s = str(t)
        return s.split("#")[0].split("[")[0].strip()

    def chain(self, ct):
        """Base-class chain of a class type, most derived first, with generics kept."""
        out = []
        b = ct
        seen = 0
        while b is not None and seen < 20:
            try:
                nm = b.name
            except Exception:
                break
            if not nm:
                break
            out.append(str(b))
            try:
                b = b.baseClass
                if b is not None:
                    b = b.canonicalType
            except Exception:
                break
            seen += 1
        return out

    # ------------------------------------------------------------------ walkers
    def walk_classes(self):
        root = self.comp.getRoot()
        scopes = []
        for unit in root.compilationUnits:
            for m in _members(unit):
                if m.kind == SK.Package:
                    scopes.append((m.name, m))
                elif m.kind == SK.ClassType:
                    scopes.append(("$unit", unit))
                    break
        for inst in root.topInstances:
            scopes.append((inst.name, inst.body))
        for scope_name, scope in scopes:
            if scope_name == "uvm_pkg":
                continue
            for m in _members(scope):
                if m.kind == SK.ClassType:
                    yield scope_name, m

    def extract_class(self, scope_name, c):
        line, end_line = self.span(c)
        base = c.baseClass
        info = {
            "name": c.name,
            "scope": scope_name,
            "file": self.file_of(c.location),
            "line": line,
            "end_line": end_line,
            "base": str(base) if base is not None else None,
            "base_name": self.type_name(base) if base is not None else None,
            "chain": self.chain(base.canonicalType) if base is not None else [],
            "properties": [],
            "methods": [],
            "constraints": [],
            "connects": [],
            "set_sequencer": [],
            "handle_assign": [],
            "creates": [],
            "config_sets": [],
            "hdl_root": None,
            "uses_sequences": [],
        }
        info["chain_names"] = [self.type_name(x) for x in info["chain"]]
        for m in _members(c):
            k = m.kind
            if k == SK.ClassProperty:
                t = m.type
                try:
                    is_class = bool(t.isClass)
                except Exception:
                    is_class = False
                try:
                    is_vif = bool(t.isVirtualInterface)
                except Exception:
                    is_vif = False
                ct = t.canonicalType
                tstr = str(t)
                dims = None
                elem_t = ct
                # unpacked arrays of classes/ports: masters[], chan_export[3]
                try:
                    if ct.isUnpackedArray or ct.isDynamicallySizedArray:
                        ar = ct
                        dims = "[]"
                        if ct.isUnpackedArray and hasattr(ct, "range"):
                            dims = f"[{ct.range.width}]"
                        elem_t = ar.elementType.canonicalType
                        is_class = bool(elem_t.isClass)
                except Exception:
                    pass
                tn = self.type_name(elem_t) if is_class else self.type_name(t)
                if is_vif:
                    tn = tstr.replace("virtual ", "").strip()
                try:
                    rand = str(m.randMode).split(".")[-1]
                except Exception:
                    rand = "None_"
                prop = {
                    "name": m.name,
                    "type": tstr,
                    "type_name": tn,
                    "is_class": is_class,
                    "is_vif": is_vif,
                    "chain": [self.type_name(x) for x in self.chain(elem_t)] if is_class else [],
                    "rand": rand in ("Rand", "RandC"),
                    "randc": rand == "RandC",
                    "dims": dims,
                    "line": self.line_of(m.location),
                    "tlm": bool(TLM_PORT_RE.match(tn)) if is_class else False,
                }
                if "covergroup" in tstr:
                    prop["type"] = "covergroup"
                    prop["type_name"] = "covergroup"
                info["properties"].append(prop)
            elif k == SK.Subroutine or str(k).endswith("MethodPrototype"):
                if m.name in MACRO_MEMBERS or m.name.startswith("__m_uvm"):
                    continue
                if self.file_of(m.location) != info["file"]:
                    continue   # macro expansion from a library file
                if k != SK.Subroutine:
                    # `extern` prototype: the body is the out-of-block definition after endclass
                    try:
                        sub = m.subroutine
                    except Exception:
                        sub = None
                    if sub is None:
                        continue
                    m = sub
                l1, l2 = self.span(m)
                flags = ""
                try:
                    flags = str(m.flags).split(".")[-1]
                except Exception:
                    flags = ""
                try:
                    skind = "task" if "Task" in str(m.subroutineKind) else "function"
                except Exception:
                    skind = "function"
                info["methods"].append({
                    "name": m.name, "kind": skind, "line": l1, "end_line": l2,
                    "virtual": "Virtual" in flags, "static": "Static" in flags,
                    "ctor": m.name == "new",
                })
                self.scan_body(m, info)
            elif k == SK.ConstraintBlock:
                txt = ""
                try:
                    txt = self.text(m.syntax.sourceRange)
                except Exception:
                    pass
                info["constraints"].append({"name": m.name, "text": txt, "line": self.line_of(m.location)})
            elif k == SK.CovergroupType or _kind(m) == "CovergroupType":
                info.setdefault("covergroups", []).append(m.name)
        # which sequences does a sequence use (declared as members)?
        for p in info["properties"]:
            if p["is_class"] and "uvm_sequence" in p["chain"] and "uvm_sequence_item" not in p["chain"]:
                info["uses_sequences"].append(p["type_name"])
        return info

    def scan_body(self, sub, info):
        """Collect connect(), set_sequencer(), create(), config set() calls and sequencer handle
        assignments inside a method body."""
        try:
            body = sub.body
        except Exception:
            return
        if body is None:
            return
        mname = sub.name
        ex = self

        def visit(node):
            if isinstance(node, pyslang.ast.CallExpression):
                try:
                    sn = node.subroutineName
                except Exception:
                    return
                args = [ex.text(a.sourceRange) for a in node.arguments]
                this = node.thisClass
                this_txt = ex.text(this.sourceRange) if this is not None else None
                call_txt = ex.text(node.sourceRange)
                callee = call_txt.split("(", 1)[0].strip()      # e.g. uvm_config_int::set
                ln = ex.line_of(node.sourceRange.start)
                if sn == "connect" and this_txt and args:
                    info["connects"].append({"this": this_txt, "arg": args[0], "line": ln, "method": mname})
                elif sn == "set_sequencer" and this_txt:
                    info["set_sequencer"].append({"map": this_txt, "seqr": args[0] if args else None,
                                                  "adapter": args[1] if len(args) > 1 else None, "line": ln})
                elif sn == "set_hdl_path_root" and args:
                    info["hdl_root"] = {"block": this_txt, "path": args[0].strip('"'), "line": ln}
                elif sn == "create" and callee.endswith("::type_id::create") and args:
                    info["creates"].append({"type": callee.split("::")[0], "name": args[0], "line": ln,
                                            "method": mname})
                elif sn == "set" and len(args) == 4 and callee.endswith("::set"):
                    info["config_sets"].append({"wrapper": callee[:-5], "ctx": args[0], "inst": args[1].strip('"'),
                                                "field": args[2].strip('"'), "value": args[3], "line": ln,
                                                "method": mname})
                elif sn in ("set_type_override_by_type", "set_type_override", "set_inst_override_by_type",
                            "set_inst_override") and args:
                    info.setdefault("overrides", []).append({
                        "kind": sn, "args": [a.replace("::get_type()", "") for a in args], "line": ln,
                        "method": mname})
                elif sn in ("raise_objection", "drop_objection", "set_drain_time", "start", "print_topology",
                            "check_config_usage", "print_factory", "set_auto_predict", "set_check_on_read",
                            "lock_model", "build"):
                    info.setdefault("notable_calls", []).append({"call": sn, "method": mname, "line": ln,
                                                                 "text": call_txt[:120]})
            elif isinstance(node, pyslang.ast.AssignmentExpression):
                try:
                    lt = node.left.type
                    if lt.isClass and any(self.type_name(x).startswith("uvm_sequencer")
                                          for x in self.chain(lt.canonicalType)):
                        info["handle_assign"].append({
                            "lhs": ex.text(node.left.sourceRange), "rhs": ex.text(node.right.sourceRange),
                            "line": ex.line_of(node.sourceRange.start)})
                except Exception:
                    pass

        try:
            body.visit(visit)
        except Exception as e:  # pragma: no cover
            print(f"[extract] visit failed in {info['name']}.{mname}: {e}", file=sys.stderr)

    # ------------------------------------------------------------------ modules
    def extract_modules(self):
        root = self.comp.getRoot()
        out = {"tops": [], "modules": {}, "vif_bindings": []}
        for inst in root.topInstances:
            out["tops"].append(inst.name)
            out["modules"][inst.name] = self.extract_instance_body(inst)
            # vif bindings: config_db set() calls in initial blocks of the UVM top
            for m in _members(inst.body):
                if m.kind == SK.ProceduralBlock:
                    def visit(node):
                        if isinstance(node, pyslang.ast.CallExpression) and node.subroutineName == "set":
                            args = [self.text(a.sourceRange) for a in node.arguments]
                            if len(args) == 4 and args[1].startswith('"'):
                                out["vif_bindings"].append({
                                    "glob": args[1].strip('"'), "field": args[2].strip('"'),
                                    "target": args[3], "line": self.line_of(node.sourceRange.start)})
                    try:
                        m.body.visit(visit)
                    except Exception:
                        pass
        return out

    def extract_instance_body(self, inst, depth=0):
        body = inst.body
        d = inst.definition
        line, end_line = self.span(d) if d is not None else (0, 0)
        info = {
            "name": inst.name, "definition": d.name if d is not None else "?",
            "kind": str(d.definitionKind).split(".")[-1].lower() if d is not None else "module",
            "file": self.file_of(d.location) if d is not None else None,
            "line": line, "end_line": end_line,
            "ports": [], "instances": [], "signals": [], "params": [], "typedefs": [],
            "tasks": [], "blocks": [], "generate": [],
        }
        try:
            for pc in inst.portConnections:
                e = pc.expression
                info.setdefault("port_connections", []).append(
                    {"port": pc.port.name, "expr": self.text(e.sourceRange) if e is not None else None})
        except Exception:
            pass
        for m in _members(body):
            k = _kind(m)
            if k == "Port":
                try:
                    info["ports"].append({"name": m.name, "dir": str(m.direction).split(".")[-1].lower(),
                                          "type": str(m.type), "line": self.line_of(m.location)})
                except Exception:
                    info["ports"].append({"name": m.name, "dir": "?", "type": "?", "line": 0})
            elif k in ("Variable", "Net"):
                if any(p["name"] == m.name for p in info["ports"]):
                    continue
                info["signals"].append({"name": m.name, "type": str(m.type), "line": self.line_of(m.location),
                                        "kind": k.lower()})
            elif k == "Parameter":
                val = ""
                try:
                    val = str(m.value)
                except Exception:
                    pass
                info["params"].append({"name": m.name, "value": val, "line": self.line_of(m.location)})
            elif k == "TypeAlias":
                try:
                    info["typedefs"].append({"name": m.name, "type": str(m.targetType.type),
                                             "line": self.line_of(m.location)})
                except Exception:
                    info["typedefs"].append({"name": m.name, "type": "?", "line": self.line_of(m.location)})
            elif k == "Subroutine":
                l1, l2 = self.span(m)
                try:
                    skind = "task" if "Task" in str(m.subroutineKind) else "function"
                except Exception:
                    skind = "task"
                args = []
                try:
                    args = [a.name for a in m.arguments]
                except Exception:
                    pass
                info["tasks"].append({"name": m.name, "kind": skind, "args": args, "line": l1, "end_line": l2})
            elif k == "ProceduralBlock":
                l1, l2 = self.span(m)
                pk = ""
                try:
                    pk = str(m.procedureKind).split(".")[-1]
                except Exception:
                    pass
                info["blocks"].append({"kind": pk, "line": l1, "end_line": l2})
            elif k == "Instance" and depth < 3:
                info["instances"].append(self.extract_instance_body(m, depth + 1))
            elif k == "GenerateBlockArray":
                entries = list(m.entries)
                g = {"name": m.name, "count": len(entries), "line": self.line_of(m.location), "instances": []}
                for i, e in enumerate(entries):
                    for x in _members(e):
                        if _kind(x) == "Instance":
                            sub = self.extract_instance_body(x, depth + 1)
                            sub["name"] = f"{m.name}[{i}].{x.name}"
                            g["instances"].append(sub)
                info["generate"].append(g)
        return info

    # --------------------------------------------------------------------- enums
    def extract_enums(self):
        out = {}
        root = self.comp.getRoot()
        for unit in root.compilationUnits:
            for pkg in _members(unit):
                if pkg.kind != SK.Package or pkg.name == "uvm_pkg":
                    continue
                for m in _members(pkg):
                    if _kind(m) == "TypeAlias":
                        try:
                            tt = m.targetType.type
                            if "enum" in str(tt):
                                vals = re.findall(r"(\w+)=", str(tt))
                                out[m.name] = {"scope": pkg.name, "values": vals, "file": self.file_of(m.location),
                                               "line": self.line_of(m.location)}
                        except Exception:
                            pass
        return out


def extract(run_f):
    """Compile one run.f and return the raw structure dictionary."""
    drv, comp = lint.compile_run_f(run_f)
    if comp is None:
        raise SystemExit(f"[extract] slang could not process {run_f}")
    # diagnostics are not reported here on purpose: lint.py does that
    ex = Extractor(comp)
    classes = {}
    for scope, c in ex.walk_classes():
        classes[c.name] = ex.extract_class(scope, c)
    mods = ex.extract_modules()
    return {
        "source": os.path.relpath(os.path.abspath(run_f), ROOT).replace(os.sep, "/"),
        "classes": classes,
        "enums": ex.extract_enums(),
        "modules": mods["modules"],
        "tops": mods["tops"],
        "vif_bindings": mods["vif_bindings"],
    }


def summary(raw):
    cls = raw["classes"]
    by_scope = {}
    for c in cls.values():
        by_scope[c["scope"]] = by_scope.get(c["scope"], 0) + 1
    lines = [f"source: {raw['source']}", f"classes: {len(cls)} {by_scope}"]
    for c in cls.values():
        if c["connects"] or c["set_sequencer"] or c["handle_assign"]:
            lines.append(f"  {c['name']}: connects={len(c['connects'])} set_sequencer={len(c['set_sequencer'])} "
                         f"handles={len(c['handle_assign'])}")
    for top in raw["tops"]:
        m = raw["modules"][top]
        lines.append(f"top {top}: instances={[i['name'] for i in m['instances']]}")
    lines.append(f"vif bindings: {len(raw['vif_bindings'])}")
    return "\n".join(lines)


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("run_f")
    ap.add_argument("--json", help="write the raw structure to this file")
    ns = ap.parse_args()
    raw = extract(ns.run_f)
    print(summary(raw))
    if ns.json:
        with open(ns.json, "w") as fh:
            json.dump(raw, fh, indent=1)
